package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CloudCoverageHbm generated by hbm2java
 */
public class CloudCoverageHbm implements java.io.Serializable {

	private int cloudCoverageId;
	private String coveragePercentage;
	private Set physicalMeasurementHbms = new HashSet(0);

	public CloudCoverageHbm() {
	}

	public CloudCoverageHbm(int cloudCoverageId, String coveragePercentage) {
		this.cloudCoverageId = cloudCoverageId;
		this.coveragePercentage = coveragePercentage;
	}

	public CloudCoverageHbm(int cloudCoverageId, String coveragePercentage,
			Set physicalMeasurementHbms) {
		this.cloudCoverageId = cloudCoverageId;
		this.coveragePercentage = coveragePercentage;
		this.physicalMeasurementHbms = physicalMeasurementHbms;
	}

	public int getCloudCoverageId() {
		return this.cloudCoverageId;
	}

	public void setCloudCoverageId(int cloudCoverageId) {
		this.cloudCoverageId = cloudCoverageId;
	}

	public String getCoveragePercentage() {
		return this.coveragePercentage;
	}

	public void setCoveragePercentage(String coveragePercentage) {
		this.coveragePercentage = coveragePercentage;
	}

	public Set getPhysicalMeasurementHbms() {
		return this.physicalMeasurementHbms;
	}

	public void setPhysicalMeasurementHbms(Set physicalMeasurementHbms) {
		this.physicalMeasurementHbms = physicalMeasurementHbms;
	}

}
