package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CurrentObservationHbm generated by hbm2java
 */
public class CurrentObservationHbm implements java.io.Serializable {

	private int currentObservationId;
	private DirectionHbm directionHbm;
	private CurrentTypeHbm currentTypeHbm;
	private SiteSamplingHbm siteSamplingHbm;
	private Date observationTime;
	private Double currentSpeedCmPs;

	public CurrentObservationHbm() {
	}

	public CurrentObservationHbm(int currentObservationId,
			DirectionHbm directionHbm, CurrentTypeHbm currentTypeHbm,
			SiteSamplingHbm siteSamplingHbm, Date observationTime) {
		this.currentObservationId = currentObservationId;
		this.directionHbm = directionHbm;
		this.currentTypeHbm = currentTypeHbm;
		this.siteSamplingHbm = siteSamplingHbm;
		this.observationTime = observationTime;
	}

	public CurrentObservationHbm(int currentObservationId,
			DirectionHbm directionHbm, CurrentTypeHbm currentTypeHbm,
			SiteSamplingHbm siteSamplingHbm, Date observationTime,
			Double currentSpeedCmPs) {
		this.currentObservationId = currentObservationId;
		this.directionHbm = directionHbm;
		this.currentTypeHbm = currentTypeHbm;
		this.siteSamplingHbm = siteSamplingHbm;
		this.observationTime = observationTime;
		this.currentSpeedCmPs = currentSpeedCmPs;
	}

	public int getCurrentObservationId() {
		return this.currentObservationId;
	}

	public void setCurrentObservationId(int currentObservationId) {
		this.currentObservationId = currentObservationId;
	}

	public DirectionHbm getDirectionHbm() {
		return this.directionHbm;
	}

	public void setDirectionHbm(DirectionHbm directionHbm) {
		this.directionHbm = directionHbm;
	}

	public CurrentTypeHbm getCurrentTypeHbm() {
		return this.currentTypeHbm;
	}

	public void setCurrentTypeHbm(CurrentTypeHbm currentTypeHbm) {
		this.currentTypeHbm = currentTypeHbm;
	}

	public SiteSamplingHbm getSiteSamplingHbm() {
		return this.siteSamplingHbm;
	}

	public void setSiteSamplingHbm(SiteSamplingHbm siteSamplingHbm) {
		this.siteSamplingHbm = siteSamplingHbm;
	}

	public Date getObservationTime() {
		return this.observationTime;
	}

	public void setObservationTime(Date observationTime) {
		this.observationTime = observationTime;
	}

	public Double getCurrentSpeedCmPs() {
		return this.currentSpeedCmPs;
	}

	public void setCurrentSpeedCmPs(Double currentSpeedCmPs) {
		this.currentSpeedCmPs = currentSpeedCmPs;
	}

}
