package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DirectionHbm generated by hbm2java
 */
public class DirectionHbm implements java.io.Serializable {

	private int directionId;
	private String direction;
	private Set physicalMeasurementHbms = new HashSet(0);
	private Set currentObservationHbms = new HashSet(0);

	public DirectionHbm() {
	}

	public DirectionHbm(int directionId, String direction) {
		this.directionId = directionId;
		this.direction = direction;
	}

	public DirectionHbm(int directionId, String direction,
			Set physicalMeasurementHbms, Set currentObservationHbms) {
		this.directionId = directionId;
		this.direction = direction;
		this.physicalMeasurementHbms = physicalMeasurementHbms;
		this.currentObservationHbms = currentObservationHbms;
	}

	public int getDirectionId() {
		return this.directionId;
	}

	public void setDirectionId(int directionId) {
		this.directionId = directionId;
	}

	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	public Set getPhysicalMeasurementHbms() {
		return this.physicalMeasurementHbms;
	}

	public void setPhysicalMeasurementHbms(Set physicalMeasurementHbms) {
		this.physicalMeasurementHbms = physicalMeasurementHbms;
	}

	public Set getCurrentObservationHbms() {
		return this.currentObservationHbms;
	}

	public void setCurrentObservationHbms(Set currentObservationHbms) {
		this.currentObservationHbms = currentObservationHbms;
	}

}
