package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * FishHbm generated by hbm2java
 */
public class FishHbm implements java.io.Serializable {

	private int fishId;
	private String name;
	private Set siteSamplingFishCountHbms = new HashSet(0);

	public FishHbm() {
	}

	public FishHbm(int fishId, String name) {
		this.fishId = fishId;
		this.name = name;
	}

	public FishHbm(int fishId, String name, Set siteSamplingFishCountHbms) {
		this.fishId = fishId;
		this.name = name;
		this.siteSamplingFishCountHbms = siteSamplingFishCountHbms;
	}

	public int getFishId() {
		return this.fishId;
	}

	public void setFishId(int fishId) {
		this.fishId = fishId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getSiteSamplingFishCountHbms() {
		return this.siteSamplingFishCountHbms;
	}

	public void setSiteSamplingFishCountHbms(Set siteSamplingFishCountHbms) {
		this.siteSamplingFishCountHbms = siteSamplingFishCountHbms;
	}

}
