package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MacroinvertebrateCollectionMethodHbm generated by hbm2java
 */
public class MacroinvertebrateCollectionMethodHbm implements
		java.io.Serializable {

	private int collectionMethodId;
	private String method;
	private Set siteSamplingMacroinvertebrateCountHbms = new HashSet(0);

	public MacroinvertebrateCollectionMethodHbm() {
	}

	public MacroinvertebrateCollectionMethodHbm(int collectionMethodId) {
		this.collectionMethodId = collectionMethodId;
	}

	public MacroinvertebrateCollectionMethodHbm(int collectionMethodId,
			String method, Set siteSamplingMacroinvertebrateCountHbms) {
		this.collectionMethodId = collectionMethodId;
		this.method = method;
		this.siteSamplingMacroinvertebrateCountHbms = siteSamplingMacroinvertebrateCountHbms;
	}

	public int getCollectionMethodId() {
		return this.collectionMethodId;
	}

	public void setCollectionMethodId(int collectionMethodId) {
		this.collectionMethodId = collectionMethodId;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public Set getSiteSamplingMacroinvertebrateCountHbms() {
		return this.siteSamplingMacroinvertebrateCountHbms;
	}

	public void setSiteSamplingMacroinvertebrateCountHbms(
			Set siteSamplingMacroinvertebrateCountHbms) {
		this.siteSamplingMacroinvertebrateCountHbms = siteSamplingMacroinvertebrateCountHbms;
	}

}
