package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MacroinvertebrateHbm generated by hbm2java
 */
public class MacroinvertebrateHbm implements java.io.Serializable {

	private int macroinvertebrateId;
	private String name;
	private Boolean active;
	private Set siteSamplingMacroinvertebrateCountHbms = new HashSet(0);

	public MacroinvertebrateHbm() {
	}

	public MacroinvertebrateHbm(int macroinvertebrateId, String name) {
		this.macroinvertebrateId = macroinvertebrateId;
		this.name = name;
	}

	public MacroinvertebrateHbm(int macroinvertebrateId, String name,
			Boolean active, Set siteSamplingMacroinvertebrateCountHbms) {
		this.macroinvertebrateId = macroinvertebrateId;
		this.name = name;
		this.active = active;
		this.siteSamplingMacroinvertebrateCountHbms = siteSamplingMacroinvertebrateCountHbms;
	}

	public int getMacroinvertebrateId() {
		return this.macroinvertebrateId;
	}

	public void setMacroinvertebrateId(int macroinvertebrateId) {
		this.macroinvertebrateId = macroinvertebrateId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public Set getSiteSamplingMacroinvertebrateCountHbms() {
		return this.siteSamplingMacroinvertebrateCountHbms;
	}

	public void setSiteSamplingMacroinvertebrateCountHbms(
			Set siteSamplingMacroinvertebrateCountHbms) {
		this.siteSamplingMacroinvertebrateCountHbms = siteSamplingMacroinvertebrateCountHbms;
	}

}
