package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PhysicalMeasurementHbm generated by hbm2java
 */
public class PhysicalMeasurementHbm implements java.io.Serializable {

	private int physicalMeasurementId;
	private CloudCoverageHbm cloudCoverageHbm;
	private WindBeaufortHbm windBeaufortHbm;
	private DirectionHbm directionHbm;
	private SiteSamplingHbm siteSamplingHbm;
	private Date measureTime;
	private Double airTemperature;
	private String weatherToday;
	private String weatherLast3Days;
	private Double windSpeed;
	private String waterCondition;
	private Double waterTemperature;

	public PhysicalMeasurementHbm() {
	}

	public PhysicalMeasurementHbm(int physicalMeasurementId,
			SiteSamplingHbm siteSamplingHbm) {
		this.physicalMeasurementId = physicalMeasurementId;
		this.siteSamplingHbm = siteSamplingHbm;
	}

	public PhysicalMeasurementHbm(int physicalMeasurementId,
			CloudCoverageHbm cloudCoverageHbm, WindBeaufortHbm windBeaufortHbm,
			DirectionHbm directionHbm, SiteSamplingHbm siteSamplingHbm,
			Date measureTime, Double airTemperature, String weatherToday,
			String weatherLast3Days, Double windSpeed, String waterCondition,
			Double waterTemperature) {
		this.physicalMeasurementId = physicalMeasurementId;
		this.cloudCoverageHbm = cloudCoverageHbm;
		this.windBeaufortHbm = windBeaufortHbm;
		this.directionHbm = directionHbm;
		this.siteSamplingHbm = siteSamplingHbm;
		this.measureTime = measureTime;
		this.airTemperature = airTemperature;
		this.weatherToday = weatherToday;
		this.weatherLast3Days = weatherLast3Days;
		this.windSpeed = windSpeed;
		this.waterCondition = waterCondition;
		this.waterTemperature = waterTemperature;
	}

	public int getPhysicalMeasurementId() {
		return this.physicalMeasurementId;
	}

	public void setPhysicalMeasurementId(int physicalMeasurementId) {
		this.physicalMeasurementId = physicalMeasurementId;
	}

	public CloudCoverageHbm getCloudCoverageHbm() {
		return this.cloudCoverageHbm;
	}

	public void setCloudCoverageHbm(CloudCoverageHbm cloudCoverageHbm) {
		this.cloudCoverageHbm = cloudCoverageHbm;
	}

	public WindBeaufortHbm getWindBeaufortHbm() {
		return this.windBeaufortHbm;
	}

	public void setWindBeaufortHbm(WindBeaufortHbm windBeaufortHbm) {
		this.windBeaufortHbm = windBeaufortHbm;
	}

	public DirectionHbm getDirectionHbm() {
		return this.directionHbm;
	}

	public void setDirectionHbm(DirectionHbm directionHbm) {
		this.directionHbm = directionHbm;
	}

	public SiteSamplingHbm getSiteSamplingHbm() {
		return this.siteSamplingHbm;
	}

	public void setSiteSamplingHbm(SiteSamplingHbm siteSamplingHbm) {
		this.siteSamplingHbm = siteSamplingHbm;
	}

	public Date getMeasureTime() {
		return this.measureTime;
	}

	public void setMeasureTime(Date measureTime) {
		this.measureTime = measureTime;
	}

	public Double getAirTemperature() {
		return this.airTemperature;
	}

	public void setAirTemperature(Double airTemperature) {
		this.airTemperature = airTemperature;
	}

	public String getWeatherToday() {
		return this.weatherToday;
	}

	public void setWeatherToday(String weatherToday) {
		this.weatherToday = weatherToday;
	}

	public String getWeatherLast3Days() {
		return this.weatherLast3Days;
	}

	public void setWeatherLast3Days(String weatherLast3Days) {
		this.weatherLast3Days = weatherLast3Days;
	}

	public Double getWindSpeed() {
		return this.windSpeed;
	}

	public void setWindSpeed(Double windSpeed) {
		this.windSpeed = windSpeed;
	}

	public String getWaterCondition() {
		return this.waterCondition;
	}

	public void setWaterCondition(String waterCondition) {
		this.waterCondition = waterCondition;
	}

	public Double getWaterTemperature() {
		return this.waterTemperature;
	}

	public void setWaterTemperature(Double waterTemperature) {
		this.waterTemperature = waterTemperature;
	}

}
