package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * RiverHbm generated by hbm2java
 */
public class RiverHbm implements java.io.Serializable {

	private int riverId;
	private String name;
	private Set riverSiteHbms = new HashSet(0);

	public RiverHbm() {
	}

	public RiverHbm(int riverId, String name) {
		this.riverId = riverId;
		this.name = name;
	}

	public RiverHbm(int riverId, String name, Set riverSiteHbms) {
		this.riverId = riverId;
		this.name = name;
		this.riverSiteHbms = riverSiteHbms;
	}

	public int getRiverId() {
		return this.riverId;
	}

	public void setRiverId(int riverId) {
		this.riverId = riverId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getRiverSiteHbms() {
		return this.riverSiteHbms;
	}

	public void setRiverSiteHbms(Set riverSiteHbms) {
		this.riverSiteHbms = riverSiteHbms;
	}

}
