package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * RiverSiteHbm generated by hbm2java
 */
public class RiverSiteHbm implements java.io.Serializable {

	private int riverSiteId;
	private RiverHbm riverHbm;
	private String name;
	private Double latitude;
	private Double longitude;
	private String description;
	private byte[] picture;
	private Double riverMile;
	private Set siteSamplingHbms = new HashSet(0);

	public RiverSiteHbm() {
	}

	public RiverSiteHbm(int riverSiteId, RiverHbm riverHbm, String name) {
		this.riverSiteId = riverSiteId;
		this.riverHbm = riverHbm;
		this.name = name;
	}

	public RiverSiteHbm(int riverSiteId, RiverHbm riverHbm, String name,
			Double latitude, Double longitude, String description,
			byte[] picture, Double riverMile, Set siteSamplingHbms) {
		this.riverSiteId = riverSiteId;
		this.riverHbm = riverHbm;
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
		this.description = description;
		this.picture = picture;
		this.riverMile = riverMile;
		this.siteSamplingHbms = siteSamplingHbms;
	}

	public int getRiverSiteId() {
		return this.riverSiteId;
	}

	public void setRiverSiteId(int riverSiteId) {
		this.riverSiteId = riverSiteId;
	}

	public RiverHbm getRiverHbm() {
		return this.riverHbm;
	}

	public void setRiverHbm(RiverHbm riverHbm) {
		this.riverHbm = riverHbm;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte[] getPicture() {
		return this.picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

	public Double getRiverMile() {
		return this.riverMile;
	}

	public void setRiverMile(Double riverMile) {
		this.riverMile = riverMile;
	}

	public Set getSiteSamplingHbms() {
		return this.siteSamplingHbms;
	}

	public void setSiteSamplingHbms(Set siteSamplingHbms) {
		this.siteSamplingHbms = siteSamplingHbms;
	}

}
