package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * SchoolSiteSamplingHbm generated by hbm2java
 */
public class SchoolSiteSamplingHbm implements java.io.Serializable {

	private int schoolSiteSamplingId;
	private SchoolHbm schoolHbm;
	private SiteSamplingHbm siteSamplingHbm;

	public SchoolSiteSamplingHbm() {
	}

	public SchoolSiteSamplingHbm(int schoolSiteSamplingId, SchoolHbm schoolHbm,
			SiteSamplingHbm siteSamplingHbm) {
		this.schoolSiteSamplingId = schoolSiteSamplingId;
		this.schoolHbm = schoolHbm;
		this.siteSamplingHbm = siteSamplingHbm;
	}

	public int getSchoolSiteSamplingId() {
		return this.schoolSiteSamplingId;
	}

	public void setSchoolSiteSamplingId(int schoolSiteSamplingId) {
		this.schoolSiteSamplingId = schoolSiteSamplingId;
	}

	public SchoolHbm getSchoolHbm() {
		return this.schoolHbm;
	}

	public void setSchoolHbm(SchoolHbm schoolHbm) {
		this.schoolHbm = schoolHbm;
	}

	public SiteSamplingHbm getSiteSamplingHbm() {
		return this.siteSamplingHbm;
	}

	public void setSiteSamplingHbm(SiteSamplingHbm siteSamplingHbm) {
		this.siteSamplingHbm = siteSamplingHbm;
	}

}
