package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SchoolHbm generated by hbm2java
 */
public class SchoolHbm implements java.io.Serializable {

	private int schoolId;
	private String name;
	private Set schoolSiteSamplingHbms = new HashSet(0);
	private Set siteSamplingHbms = new HashSet(0);

	public SchoolHbm() {
	}

	public SchoolHbm(int schoolId, String name) {
		this.schoolId = schoolId;
		this.name = name;
	}

	public SchoolHbm(int schoolId, String name, Set schoolSiteSamplingHbms,
			Set siteSamplingHbms) {
		this.schoolId = schoolId;
		this.name = name;
		this.schoolSiteSamplingHbms = schoolSiteSamplingHbms;
		this.siteSamplingHbms = siteSamplingHbms;
	}

	public int getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getSchoolSiteSamplingHbms() {
		return this.schoolSiteSamplingHbms;
	}

	public void setSchoolSiteSamplingHbms(Set schoolSiteSamplingHbms) {
		this.schoolSiteSamplingHbms = schoolSiteSamplingHbms;
	}

	public Set getSiteSamplingHbms() {
		return this.siteSamplingHbms;
	}

	public void setSiteSamplingHbms(Set siteSamplingHbms) {
		this.siteSamplingHbms = siteSamplingHbms;
	}

}
