package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SiteSamplingFishCountHbm generated by hbm2java
 */
public class SiteSamplingFishCountHbm implements java.io.Serializable {

	private int siteFishCountId;
	private FishHbm fishHbm;
	private FishingMethodHbm fishingMethodHbm;
	private SiteSamplingHbm siteSamplingHbm;
	private int amount;
	private Date samplingDate;

	public SiteSamplingFishCountHbm() {
	}

	public SiteSamplingFishCountHbm(int siteFishCountId, FishHbm fishHbm,
			SiteSamplingHbm siteSamplingHbm, int amount) {
		this.siteFishCountId = siteFishCountId;
		this.fishHbm = fishHbm;
		this.siteSamplingHbm = siteSamplingHbm;
		this.amount = amount;
	}

	public SiteSamplingFishCountHbm(int siteFishCountId, FishHbm fishHbm,
			FishingMethodHbm fishingMethodHbm, SiteSamplingHbm siteSamplingHbm,
			int amount, Date samplingDate) {
		this.siteFishCountId = siteFishCountId;
		this.fishHbm = fishHbm;
		this.fishingMethodHbm = fishingMethodHbm;
		this.siteSamplingHbm = siteSamplingHbm;
		this.amount = amount;
		this.samplingDate = samplingDate;
	}

	public int getSiteFishCountId() {
		return this.siteFishCountId;
	}

	public void setSiteFishCountId(int siteFishCountId) {
		this.siteFishCountId = siteFishCountId;
	}

	public FishHbm getFishHbm() {
		return this.fishHbm;
	}

	public void setFishHbm(FishHbm fishHbm) {
		this.fishHbm = fishHbm;
	}

	public FishingMethodHbm getFishingMethodHbm() {
		return this.fishingMethodHbm;
	}

	public void setFishingMethodHbm(FishingMethodHbm fishingMethodHbm) {
		this.fishingMethodHbm = fishingMethodHbm;
	}

	public SiteSamplingHbm getSiteSamplingHbm() {
		return this.siteSamplingHbm;
	}

	public void setSiteSamplingHbm(SiteSamplingHbm siteSamplingHbm) {
		this.siteSamplingHbm = siteSamplingHbm;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public Date getSamplingDate() {
		return this.samplingDate;
	}

	public void setSamplingDate(Date samplingDate) {
		this.samplingDate = samplingDate;
	}

}
