package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SiteSamplingHbm generated by hbm2java
 */
public class SiteSamplingHbm implements java.io.Serializable {

	private int siteSamplingId;
	private RiverSiteHbm riverSiteHbm;
	private PartnerHbm partnerHbm;
	private SchoolHbm schoolHbm;
	private Date samplingTime;
	private Set chemistryHbms = new HashSet(0);
	private Set siteSamplingMacroinvertebrateCountHbms = new HashSet(0);
	private Set siteSamplingFishCountHbms = new HashSet(0);
	private Set tideObservationHbms = new HashSet(0);
	private Set physicalMeasurementHbms = new HashSet(0);
	private Set turbidityHbms = new HashSet(0);
	private Set currentObservationHbms = new HashSet(0);
	private Set studentSalinityHbms = new HashSet(0);
	private Set schoolSiteSamplingHbms = new HashSet(0);
	private Set standardizedSalinityHbms = new HashSet(0);

	public SiteSamplingHbm() {
	}

	public SiteSamplingHbm(int siteSamplingId, RiverSiteHbm riverSiteHbm,
			SchoolHbm schoolHbm, Date samplingTime) {
		this.siteSamplingId = siteSamplingId;
		this.riverSiteHbm = riverSiteHbm;
		this.schoolHbm = schoolHbm;
		this.samplingTime = samplingTime;
	}

	public SiteSamplingHbm(int siteSamplingId, RiverSiteHbm riverSiteHbm,
			PartnerHbm partnerHbm, SchoolHbm schoolHbm, Date samplingTime,
			Set chemistryHbms, Set siteSamplingMacroinvertebrateCountHbms,
			Set siteSamplingFishCountHbms, Set tideObservationHbms,
			Set physicalMeasurementHbms, Set turbidityHbms,
			Set currentObservationHbms, Set studentSalinityHbms,
			Set schoolSiteSamplingHbms, Set standardizedSalinityHbms) {
		this.siteSamplingId = siteSamplingId;
		this.riverSiteHbm = riverSiteHbm;
		this.partnerHbm = partnerHbm;
		this.schoolHbm = schoolHbm;
		this.samplingTime = samplingTime;
		this.chemistryHbms = chemistryHbms;
		this.siteSamplingMacroinvertebrateCountHbms = siteSamplingMacroinvertebrateCountHbms;
		this.siteSamplingFishCountHbms = siteSamplingFishCountHbms;
		this.tideObservationHbms = tideObservationHbms;
		this.physicalMeasurementHbms = physicalMeasurementHbms;
		this.turbidityHbms = turbidityHbms;
		this.currentObservationHbms = currentObservationHbms;
		this.studentSalinityHbms = studentSalinityHbms;
		this.schoolSiteSamplingHbms = schoolSiteSamplingHbms;
		this.standardizedSalinityHbms = standardizedSalinityHbms;
	}

	public int getSiteSamplingId() {
		return this.siteSamplingId;
	}

	public void setSiteSamplingId(int siteSamplingId) {
		this.siteSamplingId = siteSamplingId;
	}

	public RiverSiteHbm getRiverSiteHbm() {
		return this.riverSiteHbm;
	}

	public void setRiverSiteHbm(RiverSiteHbm riverSiteHbm) {
		this.riverSiteHbm = riverSiteHbm;
	}

	public PartnerHbm getPartnerHbm() {
		return this.partnerHbm;
	}

	public void setPartnerHbm(PartnerHbm partnerHbm) {
		this.partnerHbm = partnerHbm;
	}

	public SchoolHbm getSchoolHbm() {
		return this.schoolHbm;
	}

	public void setSchoolHbm(SchoolHbm schoolHbm) {
		this.schoolHbm = schoolHbm;
	}

	public Date getSamplingTime() {
		return this.samplingTime;
	}

	public void setSamplingTime(Date samplingTime) {
		this.samplingTime = samplingTime;
	}

	public Set getChemistryHbms() {
		return this.chemistryHbms;
	}

	public void setChemistryHbms(Set chemistryHbms) {
		this.chemistryHbms = chemistryHbms;
	}

	public Set getSiteSamplingMacroinvertebrateCountHbms() {
		return this.siteSamplingMacroinvertebrateCountHbms;
	}

	public void setSiteSamplingMacroinvertebrateCountHbms(
			Set siteSamplingMacroinvertebrateCountHbms) {
		this.siteSamplingMacroinvertebrateCountHbms = siteSamplingMacroinvertebrateCountHbms;
	}

	public Set getSiteSamplingFishCountHbms() {
		return this.siteSamplingFishCountHbms;
	}

	public void setSiteSamplingFishCountHbms(Set siteSamplingFishCountHbms) {
		this.siteSamplingFishCountHbms = siteSamplingFishCountHbms;
	}

	public Set getTideObservationHbms() {
		return this.tideObservationHbms;
	}

	public void setTideObservationHbms(Set tideObservationHbms) {
		this.tideObservationHbms = tideObservationHbms;
	}

	public Set getPhysicalMeasurementHbms() {
		return this.physicalMeasurementHbms;
	}

	public void setPhysicalMeasurementHbms(Set physicalMeasurementHbms) {
		this.physicalMeasurementHbms = physicalMeasurementHbms;
	}

	public Set getTurbidityHbms() {
		return this.turbidityHbms;
	}

	public void setTurbidityHbms(Set turbidityHbms) {
		this.turbidityHbms = turbidityHbms;
	}

	public Set getCurrentObservationHbms() {
		return this.currentObservationHbms;
	}

	public void setCurrentObservationHbms(Set currentObservationHbms) {
		this.currentObservationHbms = currentObservationHbms;
	}

	public Set getStudentSalinityHbms() {
		return this.studentSalinityHbms;
	}

	public void setStudentSalinityHbms(Set studentSalinityHbms) {
		this.studentSalinityHbms = studentSalinityHbms;
	}

	public Set getSchoolSiteSamplingHbms() {
		return this.schoolSiteSamplingHbms;
	}

	public void setSchoolSiteSamplingHbms(Set schoolSiteSamplingHbms) {
		this.schoolSiteSamplingHbms = schoolSiteSamplingHbms;
	}

	public Set getStandardizedSalinityHbms() {
		return this.standardizedSalinityHbms;
	}

	public void setStandardizedSalinityHbms(Set standardizedSalinityHbms) {
		this.standardizedSalinityHbms = standardizedSalinityHbms;
	}

}
