package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;

/**
 * StandardizedSalinityHbm generated by hbm2java
 */
public class StandardizedSalinityHbm implements java.io.Serializable {

	private int standardizedSalinityId;
	private SalinityMethodHbm salinityMethodHbm;
	private SiteSamplingHbm siteSamplingHbm;
	
	@Column(name = "salinity_time", columnDefinition= "TIME WITHOUT TIME ZONE")
	private Date salinityTime;
	private Integer totalSalinityPpm;
	private String notes;

	public StandardizedSalinityHbm() {
	}

	public StandardizedSalinityHbm(int standardizedSalinityId,
			SalinityMethodHbm salinityMethodHbm, SiteSamplingHbm siteSamplingHbm) {
		this.standardizedSalinityId = standardizedSalinityId;
		this.salinityMethodHbm = salinityMethodHbm;
		this.siteSamplingHbm = siteSamplingHbm;
	}

	public StandardizedSalinityHbm(int standardizedSalinityId,
			SalinityMethodHbm salinityMethodHbm,
			SiteSamplingHbm siteSamplingHbm, Date salinityTime,
			Integer totalSalinityPpm, String notes) {
		this.standardizedSalinityId = standardizedSalinityId;
		this.salinityMethodHbm = salinityMethodHbm;
		this.siteSamplingHbm = siteSamplingHbm;
		this.salinityTime = salinityTime;
		this.totalSalinityPpm = totalSalinityPpm;
		this.notes = notes;
	}

	public int getStandardizedSalinityId() {
		return this.standardizedSalinityId;
	}

	public void setStandardizedSalinityId(int standardizedSalinityId) {
		this.standardizedSalinityId = standardizedSalinityId;
	}

	public SalinityMethodHbm getSalinityMethodHbm() {
		return this.salinityMethodHbm;
	}

	public void setSalinityMethodHbm(SalinityMethodHbm salinityMethodHbm) {
		this.salinityMethodHbm = salinityMethodHbm;
	}

	public SiteSamplingHbm getSiteSamplingHbm() {
		return this.siteSamplingHbm;
	}

	public void setSiteSamplingHbm(SiteSamplingHbm siteSamplingHbm) {
		this.siteSamplingHbm = siteSamplingHbm;
	}

	public Date getSalinityTime() {
		return this.salinityTime;
	}

	public void setSalinityTime(Date salinityTime) {
		this.salinityTime = salinityTime;
	}

	public Integer getTotalSalinityPpm() {
		return this.totalSalinityPpm;
	}

	public void setTotalSalinityPpm(Integer totalSalinityPpm) {
		this.totalSalinityPpm = totalSalinityPpm;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
