package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StudentSalinityHbm generated by hbm2java
 */
public class StudentSalinityHbm implements java.io.Serializable {

	private int studentSalinityId;
	private SalinityMethodHbm salinityMethodHbm;
	private SiteSamplingHbm siteSamplingHbm;
	private Date salinityTime;
	private Integer totalSalinityPpm;
	private String notes;

	public StudentSalinityHbm() {
	}

	public StudentSalinityHbm(int studentSalinityId,
			SalinityMethodHbm salinityMethodHbm, SiteSamplingHbm siteSamplingHbm) {
		this.studentSalinityId = studentSalinityId;
		this.salinityMethodHbm = salinityMethodHbm;
		this.siteSamplingHbm = siteSamplingHbm;
	}

	public StudentSalinityHbm(int studentSalinityId,
			SalinityMethodHbm salinityMethodHbm,
			SiteSamplingHbm siteSamplingHbm, Date salinityTime,
			Integer totalSalinityPpm, String notes) {
		this.studentSalinityId = studentSalinityId;
		this.salinityMethodHbm = salinityMethodHbm;
		this.siteSamplingHbm = siteSamplingHbm;
		this.salinityTime = salinityTime;
		this.totalSalinityPpm = totalSalinityPpm;
		this.notes = notes;
	}

	public int getStudentSalinityId() {
		return this.studentSalinityId;
	}

	public void setStudentSalinityId(int studentSalinityId) {
		this.studentSalinityId = studentSalinityId;
	}

	public SalinityMethodHbm getSalinityMethodHbm() {
		return this.salinityMethodHbm;
	}

	public void setSalinityMethodHbm(SalinityMethodHbm salinityMethodHbm) {
		this.salinityMethodHbm = salinityMethodHbm;
	}

	public SiteSamplingHbm getSiteSamplingHbm() {
		return this.siteSamplingHbm;
	}

	public void setSiteSamplingHbm(SiteSamplingHbm siteSamplingHbm) {
		this.siteSamplingHbm = siteSamplingHbm;
	}

	public Date getSalinityTime() {
		return this.salinityTime;
	}

	public void setSalinityTime(Date salinityTime) {
		this.salinityTime = salinityTime;
	}

	public Integer getTotalSalinityPpm() {
		return this.totalSalinityPpm;
	}

	public void setTotalSalinityPpm(Integer totalSalinityPpm) {
		this.totalSalinityPpm = totalSalinityPpm;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
