package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TideObservationHbm generated by hbm2java
 */
public class TideObservationHbm implements java.io.Serializable {

	private int tideObservationId;
	private SiteSamplingHbm siteSamplingHbm;
	private Date fallingStartTime;
	private Date fallingEndTime;
	private Double totalFallHeightCm;
	private Date risingStartTime;
	private Date risingEndTime;
	private Double totalRisingHeightCm;
	private String comments;

	public TideObservationHbm() {
	}

	public TideObservationHbm(int tideObservationId,
			SiteSamplingHbm siteSamplingHbm) {
		this.tideObservationId = tideObservationId;
		this.siteSamplingHbm = siteSamplingHbm;
	}

	public TideObservationHbm(int tideObservationId,
			SiteSamplingHbm siteSamplingHbm, Date fallingStartTime,
			Date fallingEndTime, Double totalFallHeightCm,
			Date risingStartTime, Date risingEndTime,
			Double totalRisingHeightCm, String comments) {
		this.tideObservationId = tideObservationId;
		this.siteSamplingHbm = siteSamplingHbm;
		this.fallingStartTime = fallingStartTime;
		this.fallingEndTime = fallingEndTime;
		this.totalFallHeightCm = totalFallHeightCm;
		this.risingStartTime = risingStartTime;
		this.risingEndTime = risingEndTime;
		this.totalRisingHeightCm = totalRisingHeightCm;
		this.comments = comments;
	}

	public int getTideObservationId() {
		return this.tideObservationId;
	}

	public void setTideObservationId(int tideObservationId) {
		this.tideObservationId = tideObservationId;
	}

	public SiteSamplingHbm getSiteSamplingHbm() {
		return this.siteSamplingHbm;
	}

	public void setSiteSamplingHbm(SiteSamplingHbm siteSamplingHbm) {
		this.siteSamplingHbm = siteSamplingHbm;
	}

	public Date getFallingStartTime() {
		return this.fallingStartTime;
	}

	public void setFallingStartTime(Date fallingStartTime) {
		this.fallingStartTime = fallingStartTime;
	}

	public Date getFallingEndTime() {
		return this.fallingEndTime;
	}

	public void setFallingEndTime(Date fallingEndTime) {
		this.fallingEndTime = fallingEndTime;
	}

	public Double getTotalFallHeightCm() {
		return this.totalFallHeightCm;
	}

	public void setTotalFallHeightCm(Double totalFallHeightCm) {
		this.totalFallHeightCm = totalFallHeightCm;
	}

	public Date getRisingStartTime() {
		return this.risingStartTime;
	}

	public void setRisingStartTime(Date risingStartTime) {
		this.risingStartTime = risingStartTime;
	}

	public Date getRisingEndTime() {
		return this.risingEndTime;
	}

	public void setRisingEndTime(Date risingEndTime) {
		this.risingEndTime = risingEndTime;
	}

	public Double getTotalRisingHeightCm() {
		return this.totalRisingHeightCm;
	}

	public void setTotalRisingHeightCm(Double totalRisingHeightCm) {
		this.totalRisingHeightCm = totalRisingHeightCm;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
