package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * TurbidityMethodHbm generated by hbm2java
 */
public class TurbidityMethodHbm implements java.io.Serializable {

	private int turbidityId;
	private String method;

	public TurbidityMethodHbm() {
	}

	public TurbidityMethodHbm(int turbidityId, String method) {
		this.turbidityId = turbidityId;
		this.method = method;
	}

	public int getTurbidityId() {
		return this.turbidityId;
	}

	public void setTurbidityId(int turbidityId) {
		this.turbidityId = turbidityId;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

}
