package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * TurbidityHbm generated by hbm2java
 */
public class TurbidityHbm implements java.io.Serializable {

	private int turbidityId;
	private SiteSamplingHbm siteSamplingHbm;
	private Double turbidity;
	private Integer turbidityMethodId;

	public TurbidityHbm() {
	}

	public TurbidityHbm(int turbidityId, SiteSamplingHbm siteSamplingHbm) {
		this.turbidityId = turbidityId;
		this.siteSamplingHbm = siteSamplingHbm;
	}

	public TurbidityHbm(int turbidityId, SiteSamplingHbm siteSamplingHbm,
			Double turbidity, Integer turbidityMethodId) {
		this.turbidityId = turbidityId;
		this.siteSamplingHbm = siteSamplingHbm;
		this.turbidity = turbidity;
		this.turbidityMethodId = turbidityMethodId;
	}

	public int getTurbidityId() {
		return this.turbidityId;
	}

	public void setTurbidityId(int turbidityId) {
		this.turbidityId = turbidityId;
	}

	public SiteSamplingHbm getSiteSamplingHbm() {
		return this.siteSamplingHbm;
	}

	public void setSiteSamplingHbm(SiteSamplingHbm siteSamplingHbm) {
		this.siteSamplingHbm = siteSamplingHbm;
	}

	public Double getTurbidity() {
		return this.turbidity;
	}

	public void setTurbidity(Double turbidity) {
		this.turbidity = turbidity;
	}

	public Integer getTurbidityMethodId() {
		return this.turbidityMethodId;
	}

	public void setTurbidityMethodId(Integer turbidityMethodId) {
		this.turbidityMethodId = turbidityMethodId;
	}

}
