package edu.columbia.riverLife.dal.implementation.hibernate.bean;

// Generated Oct 16, 2016 7:26:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * WindBeaufortHbm generated by hbm2java
 */
public class WindBeaufortHbm implements java.io.Serializable {

	private int windBeaufortId;
	private String windBeaufort;
	private Set physicalMeasurementHbms = new HashSet(0);

	public WindBeaufortHbm() {
	}

	public WindBeaufortHbm(int windBeaufortId, String windBeaufort) {
		this.windBeaufortId = windBeaufortId;
		this.windBeaufort = windBeaufort;
	}

	public WindBeaufortHbm(int windBeaufortId, String windBeaufort,
			Set physicalMeasurementHbms) {
		this.windBeaufortId = windBeaufortId;
		this.windBeaufort = windBeaufort;
		this.physicalMeasurementHbms = physicalMeasurementHbms;
	}

	public int getWindBeaufortId() {
		return this.windBeaufortId;
	}

	public void setWindBeaufortId(int windBeaufortId) {
		this.windBeaufortId = windBeaufortId;
	}

	public String getWindBeaufort() {
		return this.windBeaufort;
	}

	public void setWindBeaufort(String windBeaufort) {
		this.windBeaufort = windBeaufort;
	}

	public Set getPhysicalMeasurementHbms() {
		return this.physicalMeasurementHbms;
	}

	public void setPhysicalMeasurementHbms(Set physicalMeasurementHbms) {
		this.physicalMeasurementHbms = physicalMeasurementHbms;
	}

}
